name: Run CodeVerse Lua Bot 24/7

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Luvit and Lit
        run: |
          curl https://lit.luvit.io/install.sh | sh
          echo "$HOME/.luvit/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: |
          lit install discordia

      - name: Run Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          luvit bot.lua
