name: Run CodeVerse Lua Bot 24/7

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Luvit and Lit Manually
        run: |
          curl -L https://github.com/luvit/luvit/raw/master/get.sh | sh
          echo "$PWD" >> $GITHUB_PATH

      - name: Install Dependencies
        run: |
          ./lit install discordia

      - name: Run Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          ./luvit bot.lua
